### ISSUE TITLE
Decouple Authentication Logic from tournamentService in updateMatchInTournament Method

### ISSUE THREAD

**Issue by yekaiwu** [injaneity/CS203-Kickoff#119]
Currently, the updateMatchInTournament method in tournamentService directly receives a token, making tournamentService implicitly responsible for user authentication and authorisation. Not ideal as it mixes business logic with security concerns.

**Comment by injaneity** [comment]
Fixed with JwtTokenProvider to handle token and ClubServiceClient to handle communication from tournament to club microservices
