### ISSUE TITLE
match throwing errors during deployment

### ISSUE THREAD

**Issue by vincetyy** [injaneity/CS203-Kickoff#123]
upon deployment, the tournament microservice does not run due to `match` being a reserved keyword in MySQL 

`2024-10-26T10:43:25.114Z WARN 1 --- [Kickoff Tournament Management] [ main] o.h.t.s.i.ExceptionHandlerLoggedImpl : GenerationTarget encountered exception accepting command : Error executing DDL "create table match (id bigint not null auto_increment, club1id bigint, club1score integer not null, club2id bigint, club2score integer not null, is_over bit not null, match_number bigint, winning_club_id bigint, round_id bigint, primary key (id)) engine=InnoDB" via JDBC [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'match (id bigint not null auto_increment, club1id bigint, club1score integer not' at line 1]`

**Comment by injaneity** [comment]
match table has been renamed to "GAME"
