### ISSUE TITLE
link club to PlayerProfile

### ISSUE THREAD

**Issue by vincetyy** [injaneity/CS203-Kickoff#13]
right now, when a club is created, it does not update the club field of the captain PlayerProfile object, not sure how we want to link it. If we have a relation with it, it might be a bit messy because the caption would have 2 variables for club (one as a player, and one additional one as a captain)

**Comment by LimJingKaiJoel** [comment]
PlayerProfile needs to have an instance variable isCaptain and Captain needs to be a role for permissions to be granted for certain actions.

Right now only Club knows who the Captain is.

Also, change transferCaptaincy() method to change Role of new captain and also set the isCaptain boolean variable to true for new captain and false for old captain.
