### ISSUE TITLE
make club invite acceptance secure

### ISSUE THREAD

**Issue by vincetyy** [injaneity/CS203-Kickoff#17]
right now, invitePlayerToClub in ClubController being called with PlayerInviteRequest
```
@PostMapping("/{clubId}/invite")
public ResponseEntity<?> invitePlayerToClub(@PathVariable Long clubId, @RequestBody PlayerInviteRequest inviteRequest) {
    try {
        clubService.invitePlayerToClub(clubId, inviteRequest.getPlayerId(), inviteRequest.getCaptainId());
        return new ResponseEntity<>("Invitation sent successfully", HttpStatus.OK);
    } catch (Exception e) {
        return new ResponseEntity<>(e.getMessage(), HttpStatus.BAD_REQUEST);
    }
}
```
theoretically, another captain can change the PlayerInviteRequest in their post request, allowing them to send requests to players on behalf of another club

we need to check if there are any other ways to enforce this "captain is captain of this club"

**Comment by injaneity** [comment]
club invitation is not a feature being implemented in this application for the near future
